apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: backend
  annotations:
    # Links KSA to GSA via Workload Identity
    iam.gke.io/gcp-service-account: backend-sa@cloudstore-489011.iam.gserviceaccount.com