apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: db-credentials
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: db-password