apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: backend
spec:
  provider:
    gcpsm:
      projectID: cloudstore-489011
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: cloud-store-cluster
          serviceAccountRef:
            name: backend-ksa