apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels: 
    app: cloudstore
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app: cloudstore
    istio-injection: enabled
  
